#!/bin/bash

function allWindows () {
  windows=("$(tmux list-windows -t $session -F '#W')")
  for i in $windows; do
    tmux send -t "$session:$i" "$command" ENTER
  done
}

function doScript () {
  # make sure script exists and is readable
  if [ ! -r "$script" ]; then
    echo "$script does not exist or is not readable, exiting..."
    exit 1
  fi
  # this is for killing default window 0 when a session is created
  newSession="false"
  # work through lines of script file
  while read line; do
    # session assignments
    if [ "${line%::*}" == "session" ]; then
      session="${line#*::}"
    else
      # make sure session is assigned
      if [ -z $session ]; then
        echo "No session assigned, try 'tmux-script session (session_name) (script_name)'."
        exit 1
      fi
      # split window and command arguments
      window="${line%::*}"
      command="${line#*::}"
      # create session if not exists
      if [ ! "$(tmux list-sessions 2>/dev/null | grep ^$session:)" ]; then
        tmux new -s "$session" -d
        newSession="true"
      fi
      if [ $window == "all" ]; then
        allWindows
      else
        # create window if not exists
        if [ ! "$(tmux list-windows -t $session 2>/dev/null | grep $window)" ]; then
          tmux new-window -t "$session" -n "$window"
        fi
        # if session was just created, kill default window 0
        if [ $newSession == "true" ]; then
          tmux kill-window -t "$session:0"
          newSession="false"
        fi
        # run command from script
        tmux send -t "$session:$window" "$command" ENTER
      fi
    fi
  done < $script
}

if [ -z $1 ]; then
  echo "Usage:"
  echo "tmux-script (script_name)"
  echo "tmux-script all (session_name) '(command)'"
  echo "tmux-script session (session_name) (script_name)"
  exit 1
fi

case $1 in
  "all")
    session="$2"
    command="$3"
    allWindows
  ;;
  "session")
    session="$2"
    script="$HOME/.tmux-script/$3"
    doScript
  ;;
  *)
    script="$HOME/.tmux-script/$1"
    doScript
  ;;
esac

exit 0
